---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  labels:
    name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metabase
  template:
    metadata:
      labels:
        name: metabase
    spec:
      containers:
      - name: metabase
        image: 073351666420.dkr.ecr.us-east-1.amazonaws.com/metabase:build1-abc
        envFrom:
        - configMapRef:
            name: metabase-config
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: metabase
spec:
  selector:
    name: metabase
  ports:
  - port: 3000
    targetPort: 3000


